### PR TITLE
Split binaries to another package and upgrade to `mirage-crypto-rng.0.11.0`

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by hannesm** [comment]
This looks mostly good to me, but:
- dkim-mirage.opam should require "dns-client-mirage" {>= "7.0.0"} instead of dns-client
- mirage/dune should list "dns-client-mirage" instead of "dns-client.mirage"

**Comment by hannesm** [comment]
done in [73f57e3](https://github.com/mirage/ocaml-dkim/pull/38/commits/73f57e375d908ccd2fb9f93aadee90830434303c)

**Comment by dinosaure** [comment]
Thanks!

**Comment by hannesm** [comment]
would be great to have a release of dkim with the new dependency chain :)

**Pull request merged**
